apiVersion: v1
kind: Pod
metadata:
  name: s3-pod
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - name: s3-storage
          mountPath: /mnt/s3
  volumes:
    - name: s3-storage
      persistentVolumeClaim:
        claimName: s3-pvc