apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-app
  template:
    metadata:
      labels:
        app: s3-app
    spec:
      containers:
      - name: s3-container
        image: nginx:latest
        volumeMounts:
        - name: s3-storage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: s3-storage
        persistentVolumeClaim:
          claimName: s3-pvc
