apiVersion: v1
kind: Pod
metadata:
  name: s3-test-pod
spec:
  containers:
  - name: s3-container
    image: nginx
    volumeMounts:
    - name: s3-storage
      mountPath: "/mnt/s3"
  volumes:
  - name: s3-storage
    persistentVolumeClaim:
      claimName: s3-pvc
