apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  flexVolume:
    driver: "s3fs/fuse"
    options:
      bucket: "swapbuck4"
      accessKeyID: "AKIA2OAJT75QK5RYPOD3"
      secretAccessKey: "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"
