apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: s3
  csi:
    driver: fuse.csi.k8s.com
    volumeHandle: s3-pv
    volumeAttributes:
      bucket: mypvpvcbucket
      region: ap-south-1
    controllerExpandSecretRef:
      name: s3-secret
      namespace: default
