apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: s3
  csi:
    driver: com.amazonaws.csi.s3
    volumeHandle: mynewpvpvcbucket
    volumeAttributes:
      bucket: mynewpvpvcbucket
      region: ap-south-1