apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: s3
  csi:
    driver: s3.csi.aws.com
    volumeHandle: pvpvc15
    volumeAttributes:
      region: ap-south-1
