apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: default
type: Opaque
data:
  aws-access-key-id: AKIAZOZQFWPRELBYAGHJ
  aws-secret-access-key: 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
