apiVersion: v1
kind: Namespace
metadata:
  name: s3-csi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-csi-driver
  namespace: s3-csi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-csi
  template:
    metadata:
      labels:
        app: s3-csi
    spec:
      containers:
        - name: s3-csi-driver
          image: k8s-sigs/s3-csi-driver:latest
          ports:
            - containerPort: 10000
